version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     java: corretto11
  pre_build:
    commands:
      - pwd
      - BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's#refs/heads/##')
      - echo "Branch name: $BRANCH_NAME"
  build:
    commands:
      - pwd
      # Build & Push Docker Image
      - echo Started to build Docker image
      - ./build/app/${ENV}/build.sh
      # Deploy Fargate Service
      - echo Started to update fargate service
      - ./build/app/${ENV}/deploy.sh
  post_build:
    commands:
      - pwd
# artifacts:
#   files: